### PR TITLE
Fix path in comment text

### LINKED ISSUE #7: Improve message from dup analyzer
Example of comment from dupl analyzer: https://github.com/src-d/lookout/pull/224#discussion_r215352817

> duplicate of /tmp/gometalint178171015/provider___.github.___poster_test.go:141-164 (dupl)

Todo:
1. remove prefix of temporary directory (most probably the easiest way is to preprocess all output removing tmp dir string. It's quite unique)
2. change artificialSep so it wouldn't be displayed as markdown. Or just create directories instead. Or change separator back to "/" before posting.

### PR DESCRIPTION
**Pull request by bzz**
Fixes #7 

 - [x] log-level works
 - [x] more stable CI on SDK install
 - [x] revert paths in message text

### CODE REVIEW

File: analyzer_test.go [hunk 1]
```diff
@@ -75,3 +75,39 @@ func TestArgsCorrect(t *testing.T) {
...
+	{"tmp/a/b.go", "/tmp/tmp___.___a___.___b.go"},
+	{"a/b/c/d/e.go", "/tmp/a___.___b___.___c___.___d___.___e.go"},
+}
+
+func TestPathTransformations(t *testing.T) {
+	for _, tt := range pathTests {
+		t.Run(tt.in, func(t *testing.T) {
+			flat := faltternPath(tt.in, "/tmp")
+			if flat != tt.out {
+				t.Errorf("forward: got %q, want %q", flat, tt.out)
```
Comment (carlosms) [inline analyzer_test.go]: why not `assert.Equal(t, tt.out, faltternPath(tt.in, "/tmp"))`?

Comment (bzz) [reply analyzer_test.go]: Addressed in 1d9e1aa

File: analyzer.go [hunk 2]
```diff
@@ -127,16 +126,47 @@ func (a *Analyzer) NotifyReviewEvent(ctx context.Context, e *lookout.ReviewEvent
 	}, nil
 }
 
+// faltternPath flattens relative path and puts it inside tmp.
+func faltternPath(file string, tmp string) string {
```
Comment (carlosms) [inline analyzer.go]: typo, `flattenPath`

**Review by carlosms — APPROVED** [review]
